name: Just Do A Test Build

on:
  push:
    branches:
      - master

jobs:
  compile:
    name: Compile Code
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: tag_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Print version information
        run: |
          echo "New Tab: ${{ steps.tag_version.outputs.new_tag }}"               
          echo "Tag: ${{ steps.tag_version.outputs.tag }}"  
          echo "Part: ${{ steps.tag_version.outputs.part }}"  
















      # - name: Bump version and push tag
      #   uses: EpiData-dk/version-increment@main
      #   id: version
      #   with:
      #     scheme: semver
      #     increment: patch        

      # - name: Print version information
      #   run: |
      #     echo "Major: ${{ steps.tag_version.outputs.major-version }}"     
      #     echo "Minor: ${{ steps.tag_version.outputs.minor-version }}"     
      #     echo "Patch: ${{ steps.tag_version.outputs.patch-version }}"     
      #     echo "Version: ${{ steps.tag_version.outputs.version }}"               
      #     echo "Version Tag: ${{ steps.tag_version.outputs.v-version }}"  